import './globals.css'
import { Dosis } from 'next/font/google'

const dosis = Dosis({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${dosis.className} bg-black`}>{children}</body>
    </html>
  )
}
